name: Simple HTML Deploy

on:
  push:
	paths:
  	- 'index.html'

jobs:
  deploy:
	runs-on: ubuntu-latest

	steps:
  	- name: Checkout Code
    	uses: actions/checkout@v3

  	- name: Copy index.html via SSH
    	uses: appleboy/scp-action@v0.1.4
    	with:
      	host: ${{ secrets.SERVER_HOST }}
      	username: ${{ secrets.SERVER_USER }}
      	key: ${{ secrets.DEPLOY_KEY }}
      	source: "index.html"
      	target: "/var/www/simple-site"
